config/routes.rb
BooksManagement::Application.routes.draw do
  resources :users

  resources :categories do
    collection do
      get 'category_of_books'
      match ':id/category_of_books' => 'categories#category_of_books'
    end
  end

  resources :authors

  resources :books do
   collection do
      get 'list'
      get 'search'
      match ':key/search' => 'books#search'
    end
  end

  resource :sessions do
    collection do
      post 'login'
      get 'logout'
    end
  end

   root :to => 'sessions#login'

  match ':controller(/:action(/:id))(.:format)'
  match 'login' => "sessions#login", :as => "login"

  scope "(:locale)", :locale => /en|vi/ do
    root :to => 'books#index'
    get "books/index"
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  validates :name, presence: true

  has_many :books, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  def category_of_books
    @category = Category.find(params[:id])
    @books = @category.books
    respond_to do |format|
      format.html {}
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/category_of_books.html.erb
<h1>Listing books of Category <%= @category.name %></h1>

<table border ='1' style = 'border-collapse: collapse;' width = '100%'>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.author.name %></td>
    <td><%= book.category.name%></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>

<br />

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table id="table_id" class="tablesorter" border="1">
  <thead>
  <tr>
    <th>Name</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
</thead>

<tbody>
<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to image_tag("show.png", title: 'Show'), category %></td>
    <td><%= link_to image_tag("edit.png", title:'Edit'), edit_category_path(category) %></td>
    <td><%= link_to image_tag("delete.png", title: 'Destroy'), category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>