config/routes.rb
BooksManagement::Application.routes.draw do
  resources :users

  resources :categories do
    collection do
      get 'category_of_books'
      match ':id/category_of_books' => 'categories#category_of_books'
    end
  end

  resources :authors

  resources :books do
   collection do
      get 'list'
      get 'search'
      match ':key/search' => 'books#search'
    end
  end

  resource :sessions do
    collection do
      post 'login'
      get 'logout'
    end
  end

   root :to => 'sessions#login'

  match ':controller(/:action(/:id))(.:format)'
  match 'login' => "sessions#login", :as => "login"

  scope "(:locale)", :locale => /en|vi/ do
    root :to => 'books#index'
    get "books/index"
  end

end

app/views/layouts/_menu.html.erb
<div class="menu">
  <ul>
    <li><%= link_to t('home'),books_path %></li>

    <li><%= link_to t('books.book'),books_path %>
      <ul>
        <li><%= link_to "List Books",books_path %></li>
        <li><%= link_to "New Book",new_book_path %></li>
      </ul>
    </li>

    <li><%= link_to t('authors.author'),authors_path %>
      <ul>
        <li><%= link_to "List Authors",authors_path%></li>
        <li><%= link_to "New Author", new_author_path %></li>
      </ul>
    </li>

    <li><%= link_to t('categories.category'),categories_path %>
      <ul>
        <li><%= link_to "List Categories",categories_path %></li>
        <li><%= link_to "New Category", new_category_path%></li>
      </ul>
    </li>

    <li><%= link_to t('users.user'), users_path %>
      <ul>
        <li><%= link_to "List Users",users_path %></li>
        <li><%= link_to "New User", new_user_path %></li>
      </ul>
    </li>
  </ul>
  
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshop</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="main">

      <div id="head">
        <div id="search">
          <p>
            <%= link_to_unless I18n.locale == :en, "English", locale: :en %>
            |
            <%= link_to_unless I18n.locale == :vi, "Vietnamese", locale: :vi %>
          </p>
          <%= form_tag("books/search", method: "get") do %>
            <%= text_field_tag(:q) %>
            <%= submit_tag(t('books.search')) %>
          <% end %>
        </div>

        <div id="sign_out">
          <%= t("signin.wellcome") +" "%> <%= link_to(session[:user].fullname, session[:user]) %>
          <%= link_to button_tag(t('signin.signout')),logout_sessions_path %>
        </div>
      </div>

      <div id="head-link">
        <%= render "layouts/menu" %>
      </div>

      <div id="left">
      </div>

      <div id="content">
          <%= yield %>
      </div>

      <div id="footer">
      </div>

    </div>
  </body>
</html>